//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public int Ingreso_Id { get; set; }
        public Nullable<int> Empleado_Id { get; set; }
        public Nullable<int> Edificio_Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Edificio Edificio { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
